// <auto-generated />
namespace Covid19Handbook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class d81 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d81));
        
        string IMigrationMetadata.Id
        {
            get { return "202205081434566_d81"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
